// <auto-generated />
namespace Microsoft.AspNet.Mvc.Xml
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class Resources
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Microsoft.AspNet.Mvc.Xml.Resources", typeof(Resources).GetTypeInfo().Assembly);

        /// <summary>
        /// Invalid argument supplied to parameter '{0}'. The expected argument for this parameter is a type which is an interface and implements IEnumerable&lt;T&gt;.
        /// </summary>
        internal static string EnumerableWrapperProvider_InvalidSourceEnumerableOfT
        {
            get { return GetString("EnumerableWrapperProvider_InvalidSourceEnumerableOfT"); }
        }

        /// <summary>
        /// Invalid argument supplied to parameter '{0}'. The expected argument for this parameter is a type which is an interface and implements IEnumerable&lt;T&gt;.
        /// </summary>
        internal static string FormatEnumerableWrapperProvider_InvalidSourceEnumerableOfT(object p0)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("EnumerableWrapperProvider_InvalidSourceEnumerableOfT"), p0);
        }

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            System.Diagnostics.Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}
